### ISSUE TITLE
[Bug/Request][1.0.4] Add compatibilty with/features from "Strong and Fair Anvils"

### ISSUE THREAD

**Issue by lizfinite** [Hephaestus-Dev/TinyTweaks#1]
The Other Mod: https://www.curseforge.com/minecraft/mc-mods/strong-and-fair-anvils
The recent 1.0.4 update has started causing a crash due to your mod modifying anvils for free name changes now, I'm assuming. 

Here's a crash log with just the two mods and fabric API:
https://pastebin.com/Hj4ynpGF

If compatibility isn't that feasible, could some/all of these features be co-opted? Being able to configure them like your other tweaks would be nice as well.

**Comment by Haven-King** [comment]
Fix also uploaded to [CurseForge](https://www.curseforge.com/minecraft/mc-mods/tinytweaks/files/2957958)
