### ISSUE TITLE
Aparrently incaptible with Sodium and/or Lithium

### ISSUE THREAD

**Issue by CosmicCow** [Hephaestus-Dev/TinyTweaks#12]
Crashes!

java.lang.ClassCastException: net.minecraft.class_2258 cannot be cast to net.minecraft.class_3611

I tried to enable/disable some features, but could not find the issue.

Edit: Never mind! Found the issue. Just a fast search on the crash log. It was the bubbles column flow, disabling did the job. S2

Amazing work tho S2

**Comment by Haven-King** [comment]
Could you give me the full log? I'd like to be able to fix this if possible :)
