### ISSUE TITLE
What exactly is persistentCollide in the config for leaves?

### ISSUE THREAD

**Issue by MrKashew** [Hephaestus-Dev/TinyTweaks#16]
thonk

**Comment by MrKashew** [comment]
also would it be possible to config slowness multiplier for leaves? thanks a bunch this mod is a wonderful

**Comment by Haven-King** [comment]
Persistent leaves are leaves placed by the player. This config option exists so that users can have natural leaves and player leaves collide differently.

Also, sure, I'll add a slowness config option in the next version.

**Comment by MrKashew** [comment]
Gotcha, thanks - much appreciated!
