### ISSUE TITLE
Crash when rendering Chests within Roughly Enough Items

### ISSUE THREAD

**Issue by lizfinite** [Hephaestus-Dev/TinyTweaks#2]
Sorry to be back so soon! It would seem there's another conflicting issue with your recent chest naming addition. 
Whenever a chest would be rendered in Roughly Enough Items, the game will crash. (At least as far as I can tell, from the log)

Using the 1.0.5 update, with REI v3.6.14 and fabric API 0.10.8+build.310 to test, the issue can be recreated by loading up any world and searching the word "chest" or scrolling through until you hit a page with chests. 

Log here: https://pastebin.com/yi1EpCN7

**Comment by Haven-King** [comment]
No need to apologize! Glad you're finding bugs that I didn't even consider :)

It was also actually an issue with Ender Chests, not normal Chests, and not specific to REI. Thanks for the issue!
