### ISSUE TITLE
Crash when loading chunks nearby oceans

### ISSUE THREAD

**Issue by Samekichi** [Hephaestus-Dev/TinyTweaks#22]
- When loading chunks with too much fluid nearby (e.g. coastlines, centers of deep oceans, and possibly lava lakes in the Nether), the game will suddenly crash. This has been tested with only TinyTweaks installed. 
- A full crash report can be found [here](https://pastebin.com/3XRKehQE).

**Comment by Haven-King** [comment]
I've received a report for this issue before, but haven't had any luck reproducing it. Do you have the `BubbleColumnsFlow` tweak on or off?

**Comment by Samekichi** [comment]
It's on.
