### ISSUE TITLE
Passable BYG Leaves

### ISSUE THREAD

**Issue by cntrik** [Hephaestus-Dev/TinyTweaks#25]
BYG leaves render a suffocation overlay instead of 
![2020-09-02_04 51 01](https://user-images.githubusercontent.com/11052983/91960492-f32a9780-ecd7-11ea-83dc-2707250ec758.png)
![2020-09-02_04 51 03](https://user-images.githubusercontent.com/11052983/91960504-f6be1e80-ecd7-11ea-944b-218a9ddc69f8.png)
![2020-09-02_04 51 06](https://user-images.githubusercontent.com/11052983/91960520-f9207880-ecd7-11ea-8bab-97d64e632a29.png)
![2020-09-02_04 51 08](https://user-images.githubusercontent.com/11052983/91960530-fb82d280-ecd7-11ea-8e63-3b15ab20a36a.png)

**Comment by Haven-King** [comment]
This is an issue with how BYG registers its leaves blocks. I've opened [a pull request](https://github.com/CorgiTaco/BYG/pull/81) over there that will fix this :)

**Comment by cntrik** [comment]
Thank you
