### ISSUE TITLE
Strange bug with furnaces

### ISSUE THREAD

**Issue by IsXGeo** [Hephaestus-Dev/TinyTweaks#26]
I'm having a weird issue where If I exit my single player world and then reload it, furnaces no longer drop their item thus being destroyed completely. This happens even with only three mods enabled, tiny tweaks, mod menu and fabric api. 

Furnaces do begin to drop again if I restart the game client and load the world but upon exiting and rejoining the error re-appears.

**Comment by Haven-King** [comment]
I'll look into this tonight.

**Comment by Haven-King** [comment]
Can you confirm if this is fixed in the latest version?

**Comment by sezam920** [comment]
I made an account just to say this, its still not fixed
