### ISSUE TITLE
Incompatibility with Mending enchantment

### ISSUE THREAD

**Issue by Gomez96** [Hephaestus-Dev/TinyTweaks#27]
Mending enchant on any tool doesn't work at all.  Here's the video: https://www.youtube.com/watch?v=DpOoTtResS0&feature=emb_title

The newest version of TinyTweaks, Fabric Loader and Fabric Api doesn't help to fix this problem. I'm playing 1.16.2 version in singleplayer. Uninstalling all other mods also doesn't fix it.

**Comment by Haven-King** [comment]
Thanks, I'll fix this in the next day or two.
