### ISSUE TITLE
Block desync between client and server

### ISSUE THREAD

**Issue by Alex1331xela** [Hephaestus-Dev/TinyTweaks#28]
I'm having a really weird issue where all of the blocks visually appear as the wrong block (and act as them too, i.e. a full block that visually looks like a crop to the client causes the player to try to fall through it unsuccessfully). It is kind of hard to explain, but the blocks themselves are the same. If sand appears to the player as kelp, and the player breaks the "kelp", it drops sand. And when the player places that sand, it appears to them to place kelp. I hope the screenshots do a better job of explaining than I can…

---

Looks correct here: *(modded Fabric server, vanilla client, without TinyTweaks)*
![2020-10-06_04 56 27](https://user-images.githubusercontent.com/13511957/95181218-03c7a500-0791-11eb-9e01-98bae15e3a2c.png)

But once TinyTweaks is added server-side this happens: *(modded Fabric server, vanilla client, with TinyTweaks)*
![2020-10-06_04 50 26](https://user-images.githubusercontent.com/13511957/95181416-44bfb980-0791-11eb-883c-ef66d078f770.png)

---

I figure this is some sort of desync issue between the server knowing the correct blocks but sending the wrong blocks to the client? This issue only arose with TinyTweaks installed, and removing every other mod on the server besides TinyTweaks still caused the issue (so it couldn't be a compatibility issue with another mod). This issue also continues to happen even with everything in the config file set to `false`.

Also of note, I've only been able to test this issue with a vanilla client connecting to the modded Fabric server. I don't know if installing the mod client-side as well would fix the issue for that one client, as I'm currently only working with vanilla clients connecting to a modded Fabric server with server-side mods.

**Comment by Haven-King** [comment]
Yes, this is a registry sync issue that would be fixed if clients had TinyTweaks installed. I can look into publishing a version that works server-side only, but for now it is required to be installed on both sides.

**Comment by Alex1331xela** [comment]
Oh, my apologies then, I was using a previous version of TinyTweaks server-side on 1.16.1 without issue so I assumed it just wasn't required to be installed on the client, with only partial functionality available like that. I would definitely love a version that works server-side only, but I know it's not practical to create a whole new version for just one person, so no pressure there. I'll close the issue now, thanks for the helpful reply!
