### ISSUE TITLE
Minecraft crash

### ISSUE THREAD

**Issue by Romz24** [Hephaestus-Dev/TinyTweaks#29]
After I installed the mod, I can no longer enter the game because it just crashes. I checked on a completely clean assembly, everything is in order there, so I think that there is a compatibility problem from some mod. Can you fix this?

Mod version: 1.0.14
Fabric api: 0.24.1+build.412-1.16
mc version: 1.16.3

[crash-2020-10-21_09.29.59-server.txt](https://github.com/Hephaestus-Dev/TinyTweaks/files/5413771/crash-2020-10-21_09.29.59-server.txt)

**Comment by Haven-King** [comment]
Fixed in [1.0.15](https://www.curseforge.com/minecraft/mc-mods/tinytweaks/files/3088376). My other library wasn't being bundled properly :(

**Comment by Romz24** [comment]
@Hephaestus-Dev 

Thanks. Can you update the mod description? I did not know about the existence of a function for double opening of doors, it is not written about it anywhere.
