### ISSUE TITLE
[Issue] Modmenu labels missing on some options, also config info

### ISSUE THREAD

**Issue by IdrisQe** [Hephaestus-Dev/TinyTweaks#31]
Some options are missing hover info in Modmenu's config; most are self-explanatory (such as Leaf Collision) but in particular "bubble columns flow", I have no idea what this does, there's no hover info, and there's no info on the mod's main page either regarding this feature. Overall, probably a good idea to double-check that everything has a description.

Additionally, It'd be really nice to have comments added to the config file to explain what options do, to more easily configure it on a server, since you can't use Modmenu for servers, you need to manually edit the config, or copy the config from a singleplayer instance.

**Comment by Haven-King** [comment]
I'll add some more descriptive tooltips for those tweaks, thanks for the heads up. The bubble column one was very small, so it must have slipped my mind to add a description.

As for comments in the config file, that's a more complicated problem. I'm writing my own config library that will allow this, but none of the popular/good config libraries for Fabric do right now. It will likely be a month or two before that's possible.

**Comment by IdrisQe** [comment]
Really? That's crazy, you'd think it'd be a major feature that wouldn't even be hard to implement to a config system.

And oh gosh, as long as the library works normally with the Modmenu config and controls menus >.>
It drives me mad when mods have their own seperate config systems that don't connect to modmenu or even the vanilla controls menu (*cough*MaLiLib*cough*)

**Comment by Haven-King** [comment]
It definitely integrates with Mod Menu!

**Comment by Haven-King** [comment]
Fixed in [a recent commit](https://github.com/Hephaestus-Dev/TinyTweaks/commit/ecafbd20e32d17cdac63d3da1f55b023eeb76deb).
