### ISSUE TITLE
[?????] Server Corruption?

### ISSUE THREAD

**Issue by IdrisQe** [Hephaestus-Dev/TinyTweaks#32]
1.0.15; I just installed it on my server Fabric server running API v0.24.1 build412 and loader version 0.10.1 build209
I also installed it on my client. I joined the server, everything seemed fine, but when my partner, who does not have TinyTweaks installed (I've used it only serverside before with no problems?), but is using Fabric, joined, for some reason all of the Path blocks had been converted to Repeating Command Blocks on her end. She was even able to pick-block them in creative. Whenever I placed a path she saw it and could use it as a command block, while I had no issues.

Upon closing the server, removing Tinytweaks from the server, and re-opening it, I was able to see the problems too. Now all the path blocks were converted to planted beetroot seeds, and every single block in the game with blockstates has been screwed up horribly. I have absolutely zero idea what the hell happened, and can only assume TinyTweaks is the culprit since none of the issues were present on my client until I removed TinyTweaks. The server is destroyed now, and this is the only place I can think to turn to.

**Comment by Haven-King** [comment]
Your world should be fine, this issue only happens when the client and server are out of sync. Versions 1.0.12-1.0.15 of TinyTweaks are required to be installed on both the client and the server. This seems to have caused some confusion, so from 1.0.16 forward, I'll make sure it works passably when installed on only the server.

~~That being said, are you sure the server world is entirely broken? Could you send me your server directory in a zip file?~~

**Comment by IdrisQe** [comment]
Update: Put the mod back in the server's mods folder. With the mod enabled clientside, I started the server and joined it. All blocks were back to normal. Removed it again, problems again, put it back, back to normal. So yeah, it's TinyTweaks doing this.

**Comment by IdrisQe** [comment]
Ah. I'm unsure. I'll try removing the mod from both the server and my client and see if the world is destroyed.

**Comment by Haven-King** [comment]
Alright, thanks. Feel free to message me on Discord if you'd like (Haven King#2790).

**Comment by IdrisQe** [comment]
Sorry for the overreaction. Removing it from serverside and clientside both fixed it, and the world seems to be undamaged.
That said... Maybe a big red notification on the top of the front page would be a good idea, as I can imagine I'm not the only one who used to use TinyTweaks as solely a serverside mod back when you could >.>;;

**Comment by Haven-King** [comment]
Yep, that's why I'm going to be changing it back to being able to be used server-side only. Sorry for the confusion!
