### ISSUE TITLE
Issues with BYG and Terrestria mods.

### ISSUE THREAD

**Issue by K0-RR** [Hephaestus-Dev/TinyTweaks#33]
Hemlock and Redwood leaves from Terrestria mod aren't made passable. Green and Blue Enchanted leaves from Oh The Biomes You'll Go [FABRIC] mod glitch out when the player "enters them". Screenshots are linked below. These issues don't occur when using other [passable leaves mod](https://www.curseforge.com/minecraft/mc-mods/fabric-passable-leaves).
https://ibb.co/ZH0hVjg
https://ibb.co/r76mx8b

**Comment by K0-RR** [comment]
This is a comment from Terrestria dev - "Likely because that mod doesn't use a leaves tag instead they use an instance of class call. We won't fix this they will have to implement their checks to accomodate for mods with custom leaves."

**Comment by Haven-King** [comment]
The issue with Terrestria will be fixed in the next update.
I will make a PR to Oh The Biomes You'll Go that fixes this, as that issue is with the way they make their enchanted leaves.

**Comment by Haven-King** [comment]
Corgi Taco has published a fix for BYG: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/3090260
