### ISSUE TITLE
Server bug

### ISSUE THREAD

**Issue by Romz24** [Hephaestus-Dev/TinyTweaks#34]
If you go with a mod to a server where it is not installed, unfortunately you face a huge number of problems.
- All blocks will be replaced with completely different ones, because of this it becomes impossible to play.
![2020-10-23_03 01 51](https://user-images.githubusercontent.com/2458113/96942329-7baa0500-14dd-11eb-816e-ce9fc21aed29.png
)
- If you stand on the leaves, you will be constantly teleported back.

There is also the opposite situation, when there is a mod on the server and client, you can disable falling through the leaves using the client settings, and this will work. At the same time, other players will still fall through the leaves.

**Comment by Haven-King** [comment]
That weirdness will be fixed in the next version. There's not a whole lot I can do to fix that part of leaf collision right now.
