### ISSUE TITLE
[Suggestions/Compatibility] Leaf Decay and Grass Hitbox Tools

### ISSUE THREAD

**Issue by MechanosG** [Hephaestus-Dev/TinyTweaks#35]
First, I just found this mod and it's epic.

Second, I'd like to suggest a fast leaf decay option, as it seems like it'd be right up this mod's alley (and I wasn't able to find a fabric mod that does that for 1.16.3, although I might have just missed it/could be tagged for lower versions).  Something configurable so leaves don't just immediately vaporize, but also don't take 5 minutes to go away.

Third, the mod Croptopia has made many of it's seeds obtainable via using a hoe to break grass.  Breaking the grass by any other means won't spawn the seeds.  With TinyTweaks no-hitbox enabled, this seems to not be possible 'till you find iron for shears (I assume holding shears in one hand and a hoe in the other might work).  I suggest allowing hoes to see the hitbox of grass like shears, or a config option to enable that.  Or maybe allowing configuration of what tools show the hitbox.  Or any other means that would allow a hoe to bop the grass before obtaining iron for shears.  Just for early game QoL.  Also yes, I'm aware I can just enable grass hitbox in the config, but where's the fun in that?  :)

**Comment by Haven-King** [comment]
I'm glad you're enjoying the mod! I can definitely add a fast leaf decay option in the next version.

As for compatibility with Croptopia, I'll look into a solution for that.

**Comment by MechanosG** [comment]
Awesome.  Also quick update, I went ahead and temporarily enabled the grass hitbox to grab some seeds.  And it seems that Croptopia seeds may no longer be dropping.  They have a pretty high drop rate so I should have at least 1 by now, but not a single drop in about 100 grass, except for vanilla wheat.

**Comment by Haven-King** [comment]
I'm not really sure how Tiny Tweaks could be causing this issue with the seeds. Did you find a solution to your problem?

**Comment by Haven-King** [comment]
So it turns out Croptopia requires grass be broken with a hoe to drop their custom seeds. I've gone ahead and added hoes to the default list of items that show grass hitboxes, which is now configurable with an item tag.

**Comment by MechanosG** [comment]
Oh hey.  Yeah I think my issue with the seeds not dropping, was just some super bad RNG.  I used a hoe for all my testing, but the last test before I updated this issue, I ran out and broke like 10-20 grass in a row and didn't get a single croptopia seed, so it gave me the impression that seed dropping somehow broke.  I continued to break more grass later while not paying as close of attention not noticing seeds so I just assumed something must be bugged.  That wasn't the case though, and they started dropping at a later date.  I just forgot to update this issue.  My bad.

Thanks for the update.

**Comment by MechanosG** [comment]
So, I just tested the update.  Seems like the new leaf decay option is instant instead of just sped up?  I'm a little confused..  I was kinda hoping for the latter (sped up but not instant) in my original suggestion, as mods for past versions seem more aesthetically pleasing that way (and possibly more performant via blocks breaking over time instead of all at once?).  I'll definitely understand if that isn't/wasn't an option for some reason, and please don't take this as me complaining.  And I realize this isn't a huge deal lol.  But may I ask why part of my suggestion was thrown out in favor of instant vein miner'ish leaves?

**Comment by Haven-King** [comment]
I did it the way I did because it was the first solution that came to mind, but I think you're right that a gradual decay would be better so [I went ahead and changed it](https://www.curseforge.com/minecraft/mc-mods/tinytweaks/files/3113010) 🙂

**Comment by MechanosG** [comment]
Ah, gotcha.  Heh, I feel spoiled now.  Very cool.  Thanks.
