### ISSUE TITLE
Terrestria Redwood and Hemlock leaves aren't passable.

### ISSUE THREAD

**Issue by K0-RR** [Hephaestus-Dev/TinyTweaks#36]
I reported this some time ago, maybe you have forgotten so I thought I will remain you.
https://github.com/Hephaestus-Dev/TinyTweaks/issues/33 - "The issue with Terrestria will be fixed in the next update."

**Comment by Haven-King** [comment]
Yep, it's already fixed in my dev environment, I just need to publish it. I hope to have a build on CurseForge by the end of the day.
