### ISSUE TITLE
[Bug] Problems server-side with shulker/chest customname labels

### ISSUE THREAD

**Issue by ghost** [Hephaestus-Dev/TinyTweaks#39]
Hello, this mod's custom name label feature spams NBT query packets to servers (>3500 within a second), this is causing players using this mod to be false kicked/banned. This NBT query packet will **only receive a response from the server if the player is OP level 2 or above** (https://imgur.com/a/UT1Zitv) So unless the player is an operator they will never receive the data. Could you please disable this feature unless the player is an operator? Thank you. (P.S please be sure when you are sending packets from a fabric mod you are sending valid ones and not sending them too frequently. Every week it seems there is some fabric mod causing trouble with my anti-cheat :p)

**Comment by Haven-King** [comment]
Fixed! [Curseforge](https://www.curseforge.com/minecraft/mc-mods/tinytweaks/files/3125037)
