### ISSUE TITLE
[Suggestion] Puddles

### ISSUE THREAD

**Issue by K0-RR** [Hephaestus-Dev/TinyTweaks#44]
Puddles, [like in this outdated forge mod](https://www.curseforge.com/minecraft/mc-mods/puddles). They would appear on solid blocks when it rains. You would be able to fill a glass bottle (this would play nicely with the Dehydration mod) from them and then a puddle would disappear. After rain and a few seconds/minutes they would vanish.

![image](https://user-images.githubusercontent.com/43277609/102790758-3eaba300-43a6-11eb-9920-3a1c7501ba9a.png)

**Comment by Haven-King** [comment]
I love this idea! Sadly, I don't think it fits in TinyTweaks, but you should for sure request it in the Fabric discord server!
