### ISSUE TITLE
[Suggestion] climb tree keybind

### ISSUE THREAD

**Issue by SylisMC** [Hephaestus-Dev/TinyTweaks#46]
Logs placed by players are climbable as well and it can lead to some frustration when trying to play survival if you build with logs

An option to require sneaking to climb trees would be a phenomenal addition (in my opinion)

As always thanks for the hard work!

**Comment by Haven-King** [comment]
I'd rather not add keybinds to TinyTweaks. I will, however, go ahead and make it check for leaves, re: #45
