### ISSUE TITLE
Passable leaves issue with Blockus leaves.

### ISSUE THREAD

**Issue by K0-RR** [Hephaestus-Dev/TinyTweaks#48]
![2020-12-31_14 13 00](https://user-images.githubusercontent.com/43277609/103412970-019a9a00-4b78-11eb-9e4a-88d4285741ea.png)
![2020-12-31_14 13 13](https://user-images.githubusercontent.com/43277609/103412972-02333080-4b78-11eb-80f0-7f8794175a76.png)

Should I report this to the Blockus devs?

**Comment by Haven-King** [comment]
Yes, this is a Blockus issue.
