### ISSUE TITLE
Hitboxes on grass when Rejuvenation is enabled

### ISSUE THREAD

**Issue by Delver26** [Hephaestus-Dev/TinyTweaks#5]
Hi,

Currently when Rejuvenation is enabled, all grass hitboxes are disabled. I understand this is an expected effect.
It seems there are some side-effects to this though:

- Some plants (lilac for example) have their hitboxes removed.
- I'm unable to easily turn grass blocks into paths now. Before I could just break the grass and right click with a shovel. Now I need to hoe the block before I can convert.

If possible, it would be good to have an option to leave the hitboxes enabled, or perhaps make them enabled only when the user is crouching?

Thanks again.

**Comment by Haven-King** [comment]
Thank you for the suggestions! I believe I've addressed them all adequately, but if not, please let me know. I will try and have a new build out on CurseForge by the end of the day.

**Comment by Delver26** [comment]
Awesome, thanks for making the changes so promptly!
I've tested them all and they work as expected, great job. Jumping up while slowed in leaves feels a bit weird, but that's probably because I'd been using [https://www.curseforge.com/minecraft/mc-mods/fabric-passable-leaves](url) prior to your fixes.

All that aside, great stuff and some nice new features too 👍

**Comment by Haven-King** [comment]
Ahhh, I see. Yeah, Dex homerolled his own logic for slowing the player, while I just did it the way cobwebs do. Maybe I'll look into changing it.
