### ISSUE TITLE
Grass prevents Melon/Pumpkin from growing

### ISSUE THREAD

**Issue by sivert-io** [Hephaestus-Dev/TinyTweaks#50]
Hello! I've noticed a bug where the grass will generate so quickly that melon and pumpkins cannot "spawn" ontop of the grass-block. How do I fix this issue?

**Comment by Haven-King** [comment]
You can try reducing grass growth rate in the configs. I'll see about making it so that melons/pumpkins can replace grass as well.

**Comment by Haven-King** [comment]
Fixed in [1.2.0](https://www.curseforge.com/minecraft/mc-mods/tinytweaks/files/3198708).
