### ISSUE TITLE
Incompatible with Dropz

### ISSUE THREAD

**Issue by Zentheon** [Hephaestus-Dev/TinyTweaks#51]
The sapling autoplanting feature doesn't seem to play nicely with whatever mixins Dropz uses in the class it attempts to inject at
[log.txt](https://github.com/Hephaestus-Dev/TinyTweaks/files/5870760/log.txt)

**Comment by Haven-King** [comment]
This is entirely on their end, as they replace the entire `ItemEntity#tick` method. I could add a hacky workaround, but the correct fix for this would be for them to not replace that entire method.

**Comment by Zentheon** [comment]
Fair enough
