### ISSUE TITLE
Missing homepage tag in the fabric.mod.json file.

### ISSUE THREAD

**Issue by K0-RR** [Hephaestus-Dev/TinyTweaks#52]
Should point to the curseforge mod page.
Don't be mad for reporting something so pointless.

**Comment by Haven-King** [comment]
[I'm pretty sure it's there?](https://github.com/Hephaestus-Dev/TinyTweaks/blob/5cb7d21a02d6466ab4b3646c8b86f576e30c6de6/src/main/resources/fabric.mod.json#L12)

**Comment by K0-RR** [comment]
Well yes but no.
It should be "homepage" instead of "website" 
https://fabricmc.net/wiki/documentation:fabric_mod_json_spec
