### ISSUE TITLE
Crash Interacting with Sodium?

### ISSUE THREAD

**Issue by Bochulain** [Hephaestus-Dev/TinyTweaks#58]
I have only narrowed down that the crash involves an interaction between this mod and either Lithium, Sodium, or Phosphor. I have nearly no knowledge of programming, but the crash report seems to indicate a null pointer referencing two lines, a "class" and something with the word "Lambda" in it, and it seems to indicate it occurs during a Sodium chunk load. I don't know if that helps. 

In between each test I deleted my Config folder and all Save folders. I don't think any other files are generated with a new world and new mods. The report is attached. 
[crash-2021-02-14_15.55.29-client.txt](https://github.com/Hephaestus-Dev/TinyTweaks/files/5978530/crash-2021-02-14_15.55.29-client.txt)
I promise I'm not belaboring the point, I'm just trying to earn your trust by showing I did very thorough testing: 
I had loaded a boatload of mods before the crash and my last test was running this, Independent Pets, and Ignus Fattus. They all worked fine, including Tiny Tweaks. Then I remembered that performance mods have a reputation for breaking mods, so I tossed Sodium, Phosphor, and Lithium in there and it crashed.  I left only those in there and then added mods one by one, and the last before a crash on a new world was TinyTweaks. I loaded one of the previously stable worlds, and it crashed there too. I removed tiny tweaks, deleted configs and saves, put all the mods I'd been testing including ones I'd confirmed safe, and it ran normally, eliminating all possibilities except TT and its interaction with one of the performance mods. 
You can reach me at jesusgeorg@gmail.com if there's anything else I can do to help.

**Comment by Haven-King** [comment]
This is actually a conflict with Lithium. I will be uploading a fix momentarily.
