### ISSUE TITLE
Flint & Steel Issue

### ISSUE THREAD

**Issue by KXIIIS** [Hephaestus-Dev/TinyTweaks#7]
Hey, the flint & steel no longer lights Villagers, Piglins, and probably any entity that can be interacted with on fire. I think it's because in 1.16.1, they changed the useOnEntity method from boolean to ActionResult, and that ActionResult conflicts with the mob entity's ActionResult interactMob method. I don't know if this is fixable, and it's really not a big deal if it isn't, but I just thought I'd bring it up. Anyway, thanks for your hard work!

**Comment by Haven-King** [comment]
What a funny little bug! I've gone ahead and pushed a fix, but I don't think it's a big enough issue to bump the version (especially since I just published a different fix this morning). It'll be fixed in the next version I publish!
