### ISSUE TITLE
There is no config option to disable the equipment view in the top left

### ISSUE THREAD

**Issue by sableseyler** [Hephaestus-Dev/TinyTweaks#9]
TinyTweaks appears to add a set of equipment icons in the top left of the screen, but does not provide any configuration options for disabling or moving this display. I appreciate the gesture of adding it, but it's conflicting with other informational displays I have in that corner. Please add an option to disable it.

**Comment by Haven-King** [comment]
TinyTweaks does not add any gui elements.
